import {StyleSheet} from 'react-native';
export const GlobalStyles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  Splashscreen: {
    width: '100%',
    height: '100%',
  },
  bottomView: {
    width: '100%',
    height: 28,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    marginLeft: 30,
    position: 'absolute', //Here is the trick
    bottom: 0, //Here is the trick
  },
  subHeadingView: {
    marginLeft: 30,
  },
  heading: {
    color: '#FFFFFF',
    fontSize: 22,
    fontFamily: 'Poppins-Bold',
    fontWeight: 'bold',
  },
  subHeading: {
    color: '#FFFFFF',
    fontSize: 11,
    marginTop: 3,
    marginBottom: 3,
    fontFamily: 'Poppins-Regular',
  },
  subHeading1: {
    color: '#FFFFFF',
    fontSize: 11,
    marginTop: 3,
    marginBottom: 3,
    fontFamily: 'Poppins-Bold',
  },
  subHeading2: {
    color: '#FFFFFF',
    fontSize: 12,
    marginTop: 3,
    marginBottom: 3,
    fontFamily: 'Poppins-Bold',
  },
  TitleHeading: {
    color: '#FFFFFF',
    fontSize: 18,
    marginTop: 3,
    marginBottom: 3,
    fontFamily: 'Poppins-Bold',
  },
  TitleHeading1: {
    color: '#FFFFFF',
    fontSize: 15,
    marginTop: 3,
    marginBottom: 3,
    fontFamily: 'Poppins-Regular',
  },
  description: {
    color: '#FFFFFF',
    fontSize: 11,
    marginBottom: 5,
    width: 328,
    fontFamily: 'Poppins-Regular',
  },
  description1: {
    color: '#FFFFFF',
    fontSize: 11,
    width: 343.2,
    fontFamily: 'Poppins-Regular',
  },
  description2: {
    color: '#FFFFFF',
    fontSize: 11,
    marginTop: 5,

    fontFamily: 'Poppins-Regular',
  },
  card: {
    width: 100,
    height: 160,
    marginRight: 20,
    marginTop: 10,
    borderRadius: 30,
  },
  button: {
    backgroundColor: 'red',
    borderRadius: 20,
    elevation: 3,
    width: '40%',
    height: 40,
    marginLeft: 20,
    marginRight: 20,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  button2: {
    backgroundColor: 'white',
    borderRadius: 20,
    elevation: 3,
    width: '40%',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  buttonText: {
    fontSize: 13,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    color: '#FFFFFF',
    marginTop: 11,
    marginLeft: 8,
  },
  buttonText2: {
    fontSize: 13,
    fontFamily: 'Poppins-Bold',
    textAlign: 'center',
    color: '#000000',
    marginTop: 11,
    marginLeft: 8,
  },
});
