import {Images} from '.';

const DUMMYDATA = [
  {
    id: 1,
    type: 'png',
    source: Images.image1,
    name: 'bala vigneswaran',
    profileImage: Images.profile,
    description: 'This is awesome ...., we enjoyed a lot ',
    time: '4 mins',
    likes: 26,
  },
  {
    id: 2,
    type: 'png',
    source: Images.image2,
    name: 'philip martin',
    profileImage: Images.profile,
    description: 'This is awesome ...., we enjoyed a lot ',
    time: '4 mins',
    likes: 26,
  },
  {
    id: 3,
    // type: 'png',
    // source: Images.image3,
    type: 'video',
    source: 'https://www.rmp-streaming.com/media/big-buck-bunny-360p.mp4',
    name: 'anil gupta',
    profileImage: Images.profile,
    description:
      'Junk MTV quiz graced by fox whelps. Bawds jog, flick quartz, vex nymphs. ',
    time: '4 mins',
    likes: 26,
  },
  {
    id: 4,
    type: 'png',
    source: Images.image4,
    name: 'manimegalai hussain',
    profileImage: Images.profile,
    description: 'This is awesome ...., we enjoyed a lot ',
    time: '12 days',
    likes: 876,
  },
];

const LOOKINGFORDATA = [
  {
    id: 1,
    type: 'png',
    source: Images.image4,
    name: 'Regina',
    profileImage: Images.profile,
    description: 'This is awesome ...., we enjoyed a lot ',
    time: '4 mins',
    likes: 26,
  },
  {
    id: 2,
    type: 'png',
    source: Images.image3,
    name: 'martin guptil',
    profileImage: Images.profile,
    description:
      'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. ',
    time: '12 hours',
    likes: 97,
  },
  {
    id: 3,
    type: 'png',
    source: Images.image1,
    name: 'gupta',
    profileImage: Images.profile,
    description:
      'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium  ',
    time: '4 hours',
    likes: 56,
  },
  {
    id: 4,
    type: 'png',
    source: Images.image2,
    name: 'Vasan',
    profileImage: Images.profile,
    description:
      'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies ',
    time: '4 days',
    likes: 126,
  },
];

const AVAILABLEDATA = [
  {
    id: 1,
    type: 'png',
    source: Images.image3,
    name: 'monica',
    profileImage: Images.profile,
    description:
      'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. ',
    time: '12 hours',
    likes: 97,
  },
  {
    id: 2,
    type: 'png',
    source: Images.image2,
    name: 'martin guptil',
    profileImage: Images.profile,
    description:
      'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. ',
    time: '12 hours',
    likes: 97,
  },
  {
    id: 3,
    type: 'png',
    source: Images.image4,
    name: 'darsha gupta',
    profileImage: Images.profile,
    description:
      'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. ',
    time: '12 hours',
    likes: 97,
  },
  {
    id: 4,
    type: 'png',
    source: Images.image1,
    name: 'manimegalai',
    profileImage: Images.profile,
    description:
      'The quick, brown fox jumps over a lazy dog. DJs flock by when MTV ax quiz prog. ',
    time: '12 hours',
    likes: 97,
  },
];

const DIRECTORYDATA = [
  {
    id: 1,
    name: 'Dharshan Xerox',
    type: 'Miscellaneous',
    distance: 1.4,
    status: 'Open',
    closeTime: '10 pm',
    rating: 5.0,
    numOfPeopleRated: 2,
    profile: Images.profile,
  },
  {
    id: 2,
    name: 'Kongu Kanisha Bakery & Sweets',
    type: 'Cakes & Bakery',
    distance: 4.9,
    status: 'Closed',
    closeTime: '10 pm',
    rating: 4.9,
    numOfPeopleRated: 7,
    profile: Images.profile,
  },
  {
    id: 3,
    name: 'Thirumurugan Stores',
    type: 'General Stores',
    distance: 5.8,
    status: 'Open',
    closeTime: '10 pm',
    rating: 5.0,
    numOfPeopleRated: 2,
    profile: Images.profile,
  },
  {
    id: 4,
    name: 'Sri Kumaran Bhavan',
    type: 'Fine Dining',
    distance: 142,
    status: 'Open',
    closeTime: '10 pm',
    rating: 4.6,
    numOfPeopleRated: 377,
    profile: Images.profile,
  },
  {
    id: 5,
    name: 'Anwar',
    type: 'Bus',
    distance: 143,
    status: 'Open',
    closeTime: '10 pm',
    rating: 5.0,
    numOfPeopleRated: 5,
    profile: Images.profile,
  },
  {
    id: 6,
    name: 'Dharshan Xerox',
    type: 'Miscellaneous',
    distance: 1.4,
    status: 'Open',
    closeTime: '10 pm',
    rating: 5.0,
    numOfPeopleRated: 2,
    profile: Images.profile,
  },
  {
    id: 7,
    name: 'Thirumurugan Stores',
    type: 'General Stores',
    distance: 5.8,
    status: 'Open',
    closeTime: '10 pm',
    rating: 5.0,
    numOfPeopleRated: 2,
    profile: Images.profile,
  },
];

export {DUMMYDATA, AVAILABLEDATA, LOOKINGFORDATA, DIRECTORYDATA};
